name: Continuos Deployment workflow

on:
  push:
    branches:
      - master
env:
  HEROKU_API_KEY: ${{secrets.TOKEN_HEROKU}}
  IMAGE_NAME: registry.heroku.com/${{secrets.APP_NAME_HEROKU}}/web
  FRONT_PATH: ./front

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout front repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.FRONT_REPOSITORY_NAME }}
          path: ${{ env.FRONT_PATH }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login heroku
        run: heroku container:login
      - name: Build
        run: docker build --build-arg BASE_API_URL=${{secrets.BASE_API_URL}} --build-arg FRONT_PATH=${{env.FRONT_PATH}} -t ${{ env.IMAGE_NAME }} .
      - name: Push image
        run: docker push ${{env.IMAGE_NAME}}
      - name: Release
        run: heroku container:release web -a ${{secrets.APP_NAME_HEROKU}}
